apiVersion: v1
kind: Pod
metadata:
  name: pod-sample
  namespace: leumi
  labels:
    app: pod-app
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
  containers:
  - name: pythonapp
    image: 646360616404.dkr.ecr.us-east-1.amazonaws.com/leumi-repository:python-app
    ports:
    - name: http
      containerPort: 8080
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux
