apiVersion: v1
kind: Service
metadata:
  name: pod-service
  namespace: leumi
  labels:
    app: pod-app
spec:
  selector:
    app: pod-app
  ports:
    - name: http
      port: 443
      targetPort: 8080
  type: LoadBalancer
