apiVersion: v1
kind: Pod
metadata:
  name: pod-sample
  namespace: leumi
  labels:
    app: pod-app
spec:
  containers:
  - name: pythonapp
    image: 646360616404.dkr.ecr.us-east-1.amazonaws.com/leumi-repository:python-app
    ports:
    - name: http
      containerPort: 8080
    imagePullPolicy: Always
  nodeSelector:
    kubernetes.io/os: linux
